//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPdevices
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.devices = new HashSet<device>();
        }
    
        public int uid { get; set; }
        public string Username { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<device> devices { get; set; }
    }
}
