//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPdevices
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public device()
        {
            this.ips = new HashSet<ip>();
        }
    
        public int did { get; set; }
        public int uid { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
    
        public virtual client client { get; set; }
        public virtual ICollection<ip> ips { get; set; }
    }
}
